### ISSUE TITLE
Possible to support jumboframes?

### ISSUE THREAD

**Issue by wrouesnel** [rd235/vdeplug4#1]
I noticed MAXPACKET hasn't been appreciably increased (it's 2048) in this package - which is still too small to allow the interface to pass jumboframes.

Is there any particular reason not to set it to ~9024 or so to allow the use of jumboframes over VDE drivers?

**Comment by rd235** [comment]
On Wed, Mar 15, 2017 at 11:06:56PM -0700, Will Rouesnel wrote:
> I noticed MAXPACKET hasn't been appreciably increased (it's 2048) in this
> package - which is still too small to allow the interface to pass jumboframes.
> 
> Is there any particular reason not to set it to ~9024 or so to allow the use of
> jumboframes over VDE drivers?

You are right, there *was* no particular reason to have a low MAXPACKET value.

Now vdeplug4 supports MTU up to 9K (9126 plus ethernet headers).

Please give it a try and let me know if there are problems.

renzo
