### ISSUE TITLE
Idea: 'monitor' wire/plugin?

### ISSUE THREAD

**Issue by virtuald** [rd235/vdeplug4#10]
It feels like you can almost do this with the existing plugs, but I haven't been able to figure it out.

The idea is to connect two VDE endpoints, and one-way forward the packets flowing between them to a monitoring endpoint (so this monitor endpoint could receive the packets flowing between the two endpoints, but could not transmit to them). The intent would be for this to be useful for monitoring the traffic between the two endpoints, such as for test validation purposes.

I suspect that this would work very similarly to a switch: there would be a single control socket that the two endpoints being monitored connect to, and then a different socket that a monitor plug could connect to. Only a single plug would need to be supported for the monitor -- if a user wanted to distribute to multiple monitors you probably could use a switch in hub mode?

I'm happy to take a look at this if this sounds like it would be useful.

**Comment by rd235** [comment]
I hope to have understood your usage scenario. When I need to monitor the traffic between two vde nodes using wireshark I do the following steps
1. start a hub, e.g.
```
vde_plug null:// hub:///tmp/hub
```
2. start a vdens, turn on the interface (without assigning any IP address) and start wireshark
```
vdens vde:///tmp/hub
ip link set vde0 up
wireshark
```
3. start the communicating nodes (VM, vdens, anything)

The problem I see is that the monitoring vdens is not completely silent (e.g. wireshark shows its IPv6 router solicitations).
If this is the problem and the remaining part of the procedure fits your needs I could create a nested plugin to define "receiving only" nodes.

**Comment by virtuald** [comment]
Yeah, that's a good point. If there was a way to connect to a hub as a "receive only" node, that would meet the requirements I was thinking of.

**Comment by rd235** [comment]
Actually only IPv6 seems to generate spurious traffic.
So the following recipe should fit.

1. start a hub, e.g.
```
vde_plug null:// hub:///tmp/hub
```
2. start a vdens, turn on the interface (without assigning any IP address / **turn off ipv6**) and start wireshark
```
vdens vde:///tmp/hub
/sbin/sysctl net.ipv6.conf.all.disable_ipv6=1
ip link set vde0 up
wireshark

3. start the communicating nodes (VM, vdens, anything)

**Comment by rd235** [comment]
I have just released [vdecapture](https://github.com/virtualsquare/vdecapture).

I believe it cat fit your requests.
