### ISSUE TITLE
macvtap tap support

### ISSUE THREAD

**Issue by virtuald** [rd235/vdeplug4#9]
First, thanks so much for vdeplug! We discovered it a few months ago and it really has transformed how we use QEMU -- specifically, vdens has been a game changer for interacting with isolated guest networks in a user friendly way.

A usage that has come up is that it would be nice to bridge existing vde-based networks to the host's network stack. One way of doing that is to create a linux tap (supported by vde already) and bridge it to the host's ethernet interface, but linux bridges require taking the host interface down to connect to the bridge. 

As an alternative, macvtap (in bridge mode) allows bridging to an existing interface without needing to bring it down. When one does:

```
ip link add link $HOST_IFACE name $TAP_IFACE type macvtap mode bridge
```

Then a `/dev/tapX` file is created that can be opened, and everything else about interacting with the tap is the same. I modified the existing tap plugin to accept an absolute path (just a one line change removing `/dev/net/tun`), and it seems to work. It might make sense for someone to implement a more fully featured macvtap plugin for vde (or might be useful for some of your other projects), so I'm leaving the suggestion here.

**Comment by rd235** [comment]
Thank you virtuald.

I have just pushed a new commit including a macvlan plugin.
Please test it and let me know if there are further useful features to add.

I am glad to hear that my work is useful and appreciated.
Maybe other features could be interesting for your usage scenarios. Have you seen 'vdens --multi' to route virtual networks through a namespace or the 'vxvde' plug to create virtual LANs among VM running on several host of the physical LAN? vxvde requires no more configuration than a multicast ip address.

see:
http://wiki.virtualsquare.org/#!tutorials/vde_ns.md
http://wiki.virtualsquare.org/#!tutorials/vde_vxvde.md

renzo:  https://www.cs.unibo.it/~renzo/

**Comment by virtuald** [comment]
Thanks! I think it would be useful if you could do `macvtap://$LINK_NAME` instead of referencing the /dev/tapX explicitly, you can get the index via `SIOCGIFINDEX`.

The following python code is able to convert the link name to /dev/tapX, doing it in C should be fairly trivial:

```python
def get_tap_device(interface_name: str) -> str:
    """Converts the macvtap link name to its /dev/tapX name"""

    # Get the interface index via SIOCGIFINDEX
    sockfd = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    ifr = struct.pack("20s", interface_name.encode())
    try:
        result = fcntl.ioctl(sockfd.fileno(), SIOCGIFINDEX, ifr)
        ifr_ifindex = struct.unpack("i", result[16:])[0]
    finally:
        sockfd.close()

    return f"/dev/tap{ifr_ifindex}"
```

---

With regards to the other features you mentioned:

* I'm hoping to do a lot more stuff using vdens in the future. I hadn't thought of using it as a router, but that's a neat idea. We are currently using a separate OpenWRT VM as a router, which there are advantages/disadvantages there.
* At the moment I don't have a need to run on multiple hosts, and if I did I wouldn't want to do so in a way that mutliple users could accidentally conflict with each other without knowing

**Comment by rd235** [comment]
Thank you for the suggestion.

The latest commit include the proposed change. Now the VNL for macvtap is
macvtap://$LINK_NAME

**Comment by virtuald** [comment]
Works great, thanks! Something I noticed that probably should be in the docs is that you have to set the mac address for the macvtap link to match the VM's mac, otherwise the packets don't get forwarded correctly.

```
ip link add link $HOST_IFACE name $TAP_IFACE type macvtap mode bridge
ip link set $TAP_IFACE address $VM_MAC up
```

I assume that's just how macvtap works. Thanks again!
